{
  "formatVersion": "1.1",
  "component": {
    "group": "GradlePractice",
    "module": "router-gradle-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "router-gradle-plugin-1.0.0.jar",
          "url": "router-gradle-plugin-1.0.0.jar",
          "size": 7599,
          "sha512": "3545f8f038c3e7beebf607d471f1152a1b8905b5aef5ae19c088ef11af9d41d6736e6e2efd010dd7429de9ed95668ad1f219158fd179cd6f61c0e75a911c58d2",
          "sha256": "7e01b27e8ada03b3df5562076ff4e2966e139f119ac0dd15243cb706c6347c86",
          "sha1": "69c2c0919b779c4aabb1ffd127f3b6482bbff333",
          "md5": "cf217f1add8220943d9837ffc0761723"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "router-gradle-plugin-1.0.0.jar",
          "url": "router-gradle-plugin-1.0.0.jar",
          "size": 7599,
          "sha512": "3545f8f038c3e7beebf607d471f1152a1b8905b5aef5ae19c088ef11af9d41d6736e6e2efd010dd7429de9ed95668ad1f219158fd179cd6f61c0e75a911c58d2",
          "sha256": "7e01b27e8ada03b3df5562076ff4e2966e139f119ac0dd15243cb706c6347c86",
          "sha1": "69c2c0919b779c4aabb1ffd127f3b6482bbff333",
          "md5": "cf217f1add8220943d9837ffc0761723"
        }
      ]
    }
  ]
}
