{
  "formatVersion": "1.1",
  "component": {
    "group": "GradlePractice",
    "module": "router-gradle-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "router-gradle-plugin-1.0.0.jar",
          "url": "router-gradle-plugin-1.0.0.jar",
          "size": 27020,
          "sha512": "301b36757845d5d0242dc930c6c113fe4bf466b9c616596c7deafe49046194aa5cc3d65aebdd015ac3ff5f7acbf6040534129f9fb45ad565e3c81b41f1f06da9",
          "sha256": "41f0d25c6738507fd8c0f4bb3fc580e51bfd5a08911cdbd84c74d276eac42db3",
          "sha1": "eb910cc5881e178edca67f0c4bb57c6db4ca69f8",
          "md5": "67cad7d72d19bc63a8d24ecc1107fb29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "router-gradle-plugin-1.0.0.jar",
          "url": "router-gradle-plugin-1.0.0.jar",
          "size": 27020,
          "sha512": "301b36757845d5d0242dc930c6c113fe4bf466b9c616596c7deafe49046194aa5cc3d65aebdd015ac3ff5f7acbf6040534129f9fb45ad565e3c81b41f1f06da9",
          "sha256": "41f0d25c6738507fd8c0f4bb3fc580e51bfd5a08911cdbd84c74d276eac42db3",
          "sha1": "eb910cc5881e178edca67f0c4bb57c6db4ca69f8",
          "md5": "67cad7d72d19bc63a8d24ecc1107fb29"
        }
      ]
    }
  ]
}
