{
  "formatVersion": "1.1",
  "component": {
    "group": "GradlePractice",
    "module": "router-gradle-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "router-gradle-plugin-1.0.0.jar",
          "url": "router-gradle-plugin-1.0.0.jar",
          "size": 38048,
          "sha512": "e45cc0e9cf0d44f4958fff3ca0070e1e0e03179e531d9c0a6e68d95fc1dd5af00a5efe3935ad3a1bfd8e68d85d6205d386faa9996cf7c1578a2ea3f1fdfde5ca",
          "sha256": "632120255f4b3da73cb968bc453f7956cf7adc214edf23324ed4b6c81dad77b0",
          "sha1": "04a9f90fee9ca9e530c0e72cd8f9dc74f70bf847",
          "md5": "c99dbad6594b881ad4d2b3be91bc6db7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "router-gradle-plugin-1.0.0.jar",
          "url": "router-gradle-plugin-1.0.0.jar",
          "size": 38048,
          "sha512": "e45cc0e9cf0d44f4958fff3ca0070e1e0e03179e531d9c0a6e68d95fc1dd5af00a5efe3935ad3a1bfd8e68d85d6205d386faa9996cf7c1578a2ea3f1fdfde5ca",
          "sha256": "632120255f4b3da73cb968bc453f7956cf7adc214edf23324ed4b6c81dad77b0",
          "sha1": "04a9f90fee9ca9e530c0e72cd8f9dc74f70bf847",
          "md5": "c99dbad6594b881ad4d2b3be91bc6db7"
        }
      ]
    }
  ]
}
