{
  "formatVersion": "1.1",
  "component": {
    "group": "GradlePractice",
    "module": "router-gradle-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "router-gradle-plugin-unspecified.jar",
          "url": "router-gradle-plugin-unspecified.jar",
          "size": 19286,
          "sha512": "73c10022fc47d425c759e993fdbd75fafa15c1bc4cc2f4d61b2214b562d8390eadbcebdee149ce6beccb270f64df92339cc48a48c0c97601505f2287d670cc49",
          "sha256": "725fb9546c1d6f75f507bb964acbae27f0bdafbf060bf9155ecf56ae5b50070b",
          "sha1": "dfbd6974572a6b6005120ab3b598c176b4bb7de7",
          "md5": "ec2da823d78426d2f59e3ec52b7c5f57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "router-gradle-plugin-unspecified.jar",
          "url": "router-gradle-plugin-unspecified.jar",
          "size": 19286,
          "sha512": "73c10022fc47d425c759e993fdbd75fafa15c1bc4cc2f4d61b2214b562d8390eadbcebdee149ce6beccb270f64df92339cc48a48c0c97601505f2287d670cc49",
          "sha256": "725fb9546c1d6f75f507bb964acbae27f0bdafbf060bf9155ecf56ae5b50070b",
          "sha1": "dfbd6974572a6b6005120ab3b598c176b4bb7de7",
          "md5": "ec2da823d78426d2f59e3ec52b7c5f57"
        }
      ]
    }
  ]
}
