{
  "formatVersion": "1.1",
  "component": {
    "group": "GradlePractice",
    "module": "router-gradle-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "router-gradle-plugin-unspecified.jar",
          "url": "router-gradle-plugin-unspecified.jar",
          "size": 32094,
          "sha512": "5115d0cf9c27b17258115fb84cf57606647b451196ca92f5e34f7dc78d23341bd79f61cc951599de7f97caa914836980791a22671ea19006c6d7af8345779eee",
          "sha256": "35b131c2ca0a05729d84ba6fcd9f78065c8b3e6101d84e67506376b702cbd0d1",
          "sha1": "f03c3bfaae47fa1b6528d2320b8be0e1158c5d88",
          "md5": "b19e613ce6bd1c8785cd9423f8b4b57f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "router-gradle-plugin-unspecified.jar",
          "url": "router-gradle-plugin-unspecified.jar",
          "size": 32094,
          "sha512": "5115d0cf9c27b17258115fb84cf57606647b451196ca92f5e34f7dc78d23341bd79f61cc951599de7f97caa914836980791a22671ea19006c6d7af8345779eee",
          "sha256": "35b131c2ca0a05729d84ba6fcd9f78065c8b3e6101d84e67506376b702cbd0d1",
          "sha1": "f03c3bfaae47fa1b6528d2320b8be0e1158c5d88",
          "md5": "b19e613ce6bd1c8785cd9423f8b4b57f"
        }
      ]
    }
  ]
}
