{
  "formatVersion": "1.1",
  "component": {
    "group": "GradlePractice",
    "module": "router-gradle-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "router-gradle-plugin-unspecified.jar",
          "url": "router-gradle-plugin-unspecified.jar",
          "size": 27064,
          "sha512": "791ac9879b24d43ec436e775c0bf02b09f3b30dc6279306e1b0ef131f512e64219553a5f4b29230a991ebb19e50ee06d97c88cf3e45d0aaba44b070d3149ca7b",
          "sha256": "0dc3484d874a2abe0022285b5d9e9e25c25358be0092d00a591046a36e2acd1a",
          "sha1": "8e7db085337c4ea19efa0b24ed208bcac4ccc6f5",
          "md5": "ee35a657708f257b396689d853c694c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "router-gradle-plugin-unspecified.jar",
          "url": "router-gradle-plugin-unspecified.jar",
          "size": 27064,
          "sha512": "791ac9879b24d43ec436e775c0bf02b09f3b30dc6279306e1b0ef131f512e64219553a5f4b29230a991ebb19e50ee06d97c88cf3e45d0aaba44b070d3149ca7b",
          "sha256": "0dc3484d874a2abe0022285b5d9e9e25c25358be0092d00a591046a36e2acd1a",
          "sha1": "8e7db085337c4ea19efa0b24ed208bcac4ccc6f5",
          "md5": "ee35a657708f257b396689d853c694c7"
        }
      ]
    }
  ]
}
